---
# tasks file for install_reverse_proxy_nginx
- name: Install Nginx
  apt: name=nginx state=latest update_cache=true

- name: Generate Config Nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default mode=0644

- name: Restart Nginx service
  systemd:
    name: nginx
    state: restarted
